# Specify additional command line arguments
- arguments: [--color, --cpp-simple, -XQuasiQuotes]

# Control which extensions/flags/modules/functions can be used

- functions:
  # unsafePerformIO can only appear in no modules
  - {name: unsafePerformIO, within: []}

# Add custom hints for this project

# Will suggest replacing "wibbleMany [myvar]" with "wibbleOne myvar"
- error: {lhs: "wibbleMany [x]", rhs: wibbleOne x}

# Turn on hints that are off by default

# Ban "module X(module X) where", to require a real export list
- warn: {name: Use explicit module export list}

# Replace a $ b $ c with a . b $ c
#- group: {name: dollar, enabled: true}

# Generalise map to fmap, ++ to <>
#- group: {name: generalise, enabled: true}
