[package]
name = "prime-factors"
description = "https://www.codewars.com/kata/54d496788776e49e6b00052f"
homepage = "https://github.com/matyama/codewars"
readme = "../README.md"
version = "0.1.0"
authors = ["Martin Matyášek <martin.matyasek@gmail.com>"]
edition = "2018"

[dependencies]
