[package]
name = "population-growth"
description = "https://www.codewars.com/kata/563b662a59afc2b5120000c6"
homepage = "https://github.com/matyama/codewars"
readme = "../README.md"
version = "0.1.0"
authors = ["Martin Matyášek <martin.matyasek@gmail.com>"]
edition = "2018"

[dependencies]
