[package]
name = "algebraic-lists"
description = "https://www.codewars.com/kata/529a92d9aba78c356b000353"
homepage = "https://github.com/matyama/codewars"
readme = "../README.md"
version = "0.1.0"
authors = ["Martin Matyášek <martin.matyasek@gmail.com>"]
edition = "2018"

[dependencies]
