[workspace]
members = [
    "algebraic-lists",
    "best-travel",
    "bouncing-balls",
    "caa-stats",
    "count-duplicates",
    "delete-nth",
    "dubstep",
    "in-array",
    "molecule",
    "parts-sums",
    "perimeter",
    "persistent-bugger",
    "population-growth",
    "product-fib",
    "simple-graph",
    "snail",
    "validate-sudoku",
]

