[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2021"
license = "MIT"

[dev-dependencies]
codewars = { version = "0.1.0", path = ".." }

[[example]]
name = "primes"
path = "primes.rs"
