[package]
name = "simple-graph"
description = "https://www.codewars.com/kata/60815326bbb0150009f55f7e/rust"
homepage = "https://github.com/matyama/codewars"
readme = "../README.md"
version = "0.1.0"
authors = ["Martin Matyášek <martin.matyasek@gmail.com>"]
edition = "2018"

[dependencies]
