[package]
name = "bouncing-balls"
description = "https://www.codewars.com/kata/5544c7a5cb454edb3c000047"
homepage = "https://github.com/matyama/codewars"
readme = "../README.md"
version = "0.1.0"
authors = ["Martin Matyášek <martin.matyasek@gmail.com>"]
edition = "2018"

[dependencies]
