[package]
name = "in-array"
description = "https://www.codewars.com/kata/550554fd08b86f84fe000a58"
homepage = "https://github.com/matyama/codewars"
readme = "../README.md"
version = "0.1.0"
authors = ["Martin Matyášek <martin.matyasek@gmail.com>"]
edition = "2018"

[dependencies]
rstest = "0.11"
