[package]
name = "delete-nth"
description = "https://www.codewars.com/kata/554ca54ffa7d91b236000023"
homepage = "https://github.com/matyama/codewars"
readme = "../README.md"
version = "0.1.0"
authors = ["Martin Matyášek <martin.matyasek@gmail.com>"]
edition = "2018"

[dependencies]
