[package]
name = "dubstep"
description = "https://www.codewars.com/kata/551dc350bf4e526099000ae5"
homepage = "https://github.com/matyama/codewars"
readme = "../README.md"
version = "0.1.0"
authors = ["Martin Matyášek <martin.matyasek@gmail.com>"]
edition = "2018"

[dependencies]
