name: Codewars

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: 1.1.2
    - name: Install dependencies
      run: poetry install
    - name: Run lint and type checks
      run: poetry run make lint
    - name: Run tests
      run: poetry run make tests
  
  rust:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    defaults:
      run:
        working-directory: rust
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --all-features --no-fail-fast
