name: Codewars

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  haskell:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: haskell
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Haskell Stack
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-no-global: true
          stack-version: latest
      - name: Cache Stack
        id: cache-stack
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            **/.stack-work
          key: cache-stack-${{ hashFiles('**/package.yaml', '**/stack.yaml', '**/dependencies.dev') }}
      - name: Install dependencies
        if: ${{ !steps.cache-stack.outputs.cache-hit }}
        run: make setup-dev
      - name: Build
        run: make build
      - name: Run tests
        run: make test
      - name: Run lints
        run: make lint
  
  python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.2.0
    - name: Install dependencies
      run: poetry install
    - name: Run lint and type checks
      run: poetry run make lint
    - name: Run tests
      run: poetry run make tests
  
  rust:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    defaults:
      run:
        working-directory: rust
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run checks
      run: cargo clippy --all-features -- -D warnings
    - name: Run tests
      run: cargo test --all-features --no-fail-fast
  
  sql:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sql
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: "3.10"
    - name: Install SQLFluff
      run: pip install sqlfluff==2.3.5
    - name: Run lint
      run: sqlfluff lint scripts
