name: Codewars

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  haskell:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: haskell
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Haskell Stack
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-no-global: true
          stack-version: latest
      - name: Cache Stack
        uses: actions/cache@v2
        with:
          path: |
            .stack
            **/.stack-work
          key: ${{ runner.os }}-cache-stack-${{ hashFiles('**/package.yaml', '**/stack.yaml') }}
      - name: Install dependencies
        run: make setup-dev
      - name: Build
        run: make build
      - name: Run tests
        run: make test
      - name: Run lints
        run: make lint
  
  python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: 1.1.2
    - name: Install dependencies
      run: poetry install
    - name: Run lint and type checks
      run: poetry run make lint
    - name: Run tests
      run: poetry run make tests
  
  rust:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    defaults:
      run:
        working-directory: rust
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run checks
      run: cargo clippy --all-features -- -D warnings
    - name: Run tests
      run: cargo test --all-features --no-fail-fast
